# Generated by Django 3.0.7 on 2021-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(max_length=100)),
                ('Ladder_score', models.IntegerField()),
                ('Logged_GDP_per_capita', models.IntegerField()),
                ('Healthy_life_expectancy', models.IntegerField()),
                ('Generosity', models.IntegerField()),
            ],
        ),
    ]
